version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: servicelink-postgres-staging
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: servicelink
    ports:
      - "5432:5432"
    volumes:
      - pgdata_stage:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: servicelink-redis-staging
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    container_name: servicelink-api-staging
    environment:
      PORT: 3001
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/servicelink
      REDIS_URL: redis://redis:6379
      JWT_SECRET: change-me
      STRIPE_RETURN_URL: http://localhost:3000/provider/onboarding/completed
      STRIPE_REFRESH_URL: http://localhost:3000/provider/onboarding/refresh
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    container_name: servicelink-web-staging
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
      ENABLE_STRICT_CSP: "true"
      CSP_STRICT_LEVEL: balanced
    depends_on:
      - api
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.27-alpine
    container_name: servicelink-nginx-staging
    depends_on:
      - web
      - api
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata_stage:
