services:
  - type: web
    name: servicelink-api
    env: node
    plan: starter
    buildCommand: pnpm i && pnpm -w build && pnpm --filter api build
    startCommand: pnpm --filter api start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: servicelink-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: servicelink-redis
          type: redis
  - type: web
    name: servicelink-web
    env: static
    buildCommand: pnpm i && pnpm --filter web build
    staticPublishPath: apps/web/out
databases:
  - name: servicelink-db
redis:
  - name: servicelink-redis
